#!/bin/bash
# Source after setting GPLSI_BENCHMARK_ROOT; use the caller's Python environment.
set -euo pipefail
GPLSI_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GPLSI_RUN_ROOT="${GPLSI_BENCHMARK_ROOT:-$GPLSI_SOURCE}"
mkdir -p "$GPLSI_RUN_ROOT"
GPLSI_RUN_ROOT="$(cd "$GPLSI_RUN_ROOT" && pwd)"
export GPLSI_BENCHMARK_ROOT="$GPLSI_RUN_ROOT"
export PYTHONPATH="$GPLSI_SOURCE/src:$GPLSI_SOURCE${PYTHONPATH:+:$PYTHONPATH}"
export XDG_CACHE_HOME="$GPLSI_RUN_ROOT/.cache/joint_v2"
export MPLCONFIGDIR="$XDG_CACHE_HOME/matplotlib" NUMBA_CACHE_DIR="$XDG_CACHE_HOME/numba"
export R_USER_CACHE_DIR="$XDG_CACHE_HOME/R" PIP_CACHE_DIR="$XDG_CACHE_HOME/pip"
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1
export TMPDIR="$GPLSI_RUN_ROOT/data/interim/joint_v2/job_tmp_${SLURM_JOB_ID:-local}_${SLURM_ARRAY_TASK_ID:-0}"
mkdir -p "$TMPDIR" "$MPLCONFIGDIR" "$NUMBA_CACHE_DIR" "$R_USER_CACHE_DIR" "$PIP_CACHE_DIR"
